from cachedfetchtest import *
from commandlinetest import *
from compilertests import *
from configtests import *
from fetchtests import *
from filenamestest import *
from folderwatchertest import *
from mainlooptest import *
from versioningtests import *